# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Switcharoohelper Unit Tests

on:
  push:
    branches: [ master, production ]
  pull_request:
    branches: [ master, production ]
  workflow_run:
    workflows: ["Deploy to Production"]
    branches: [ production ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Action Tests
      run: |
        python -m unittest -v tests.action
    - name: Parse Tests
      run: |
        python -m unittest -v tests.parse
    - name: Process Tests
      run: |
        python -m unittest -v tests.process
